apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fanly
  namespace: fanly
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fanly.example.com
      secretName: fanly-tls
  rules:
    - host: fanly.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fanly
                port:
                  name: http
